export class PointBoxBerryResponse {
  Code: string; //"37231",
  Name: string; //"Иваново Громобоя_3723_С",
  CityCode: string; //"17",
  Address: string; //"153002, Иваново г, Громобоя ул, д.11/88",
  Phone: string; //"8-800-234-80-00",
  WorkShedule: string; //"пн-пт: 10.00-19.00, сб: 10.00-17.00",
  TripDescription: string; //"Остановка: \"Площадь Ленина\". \nРасстояние от остановки до отделения 100 м. по ул. Громобоя.\nЖилой 5-ти этажный дом. \nКрупная вывеска - \"КОМПЬЮТЕРЫ\"  ТехноПрофи37\nЦентральный вход. Цокольный этаж.",
  DeliveryPeriod: number; //1,
  CityName: string; //"Иваново",
  TariffZone: string; //"2",
  Settlement: string; //"Иваново",
  Area: string; //"Ивановская обл",
  Country: string; //"РОССИЯ",
  GPS: string; //"57.010832,40.973175",
  AddressReduce: string; //"Громобоя ул, д.11/88",
  Acquiring: string; //"Yes",
  DigitalSignature: string; //"No",
  TypeOfOffice: string; //"СПВЗ",
  Metro: string; //"",
  LoadLimit: number; //31,
  VolumeLimit: string; //"0.19",
  CountryCode: string; //"643",
  NalKD: string; //"No",
  OnlyPrepaidOrders: string; //"No",
  Postamat: boolean; //false
}
